**1. Data Processing:**

In [1]:
# Import dependencies
import sys
import os

# Add the src directory to the system path
sys.path.append(os.path.abspath(os.path.join('..')))

# Import the collect_data function
from src.data_collection import collect_data

# import the clean_data function
from src.data_cleaning import clean_data

# Run collect_data function
data, _, _, _, _, _, _, _, _  = collect_data()

# Run clean_data function
data_cleaned = clean_data(data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

Label encoding of target column

In [2]:
from src.data_processing import encode_labels

# Run encode_labels function
data_encoded = encode_labels(data_cleaned)
data_encoded.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65,1

Training and Test data split

In [3]:
# Splitting features and target columns
from src.train_test_split import split_data

X, Y = split_data(data_encoded)

In [4]:
X

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,29.85
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1889.50
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,108.15
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1840.75
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1990.50
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,7362.90
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,346.45
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,306.60
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,6844.50

In [5]:
Y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

In [6]:
# Splitting features and target columns
from src.train_test_split import split_train_test_data

X_train, X_test, Y_train, Y_test = split_train_test_data(X, Y)

In [7]:
print(Y_train.shape, Y_test.shape)
print(X_train.shape, X_test.shape)

(5634,) (1409,)
(5634, 19) (1409, 19)

In [8]:
print(Y_train.value_counts())
print(Y_test.value_counts())

Churn
0    4138
1    1496
Name: count, dtype: int64
Churn
0    1036
1     373
Name: count, dtype: int64

Synthetic Minority Oversampling TEchnique (SMOTE)

In [ ]:
# Import handle_target_imbalance
from src.data_processing import handle_target_imbalance

# handle target imbalance using oversampling
X_train, Y_train = handle_target_imbalance(X_train, Y_train)
print(Y_train.value_counts())
print(Y_test.value_counts())

Churn
0    4138
1    4138
Name: count, dtype: int64
Churn
0    1036
1     373
Name: count, dtype: int64

In [10]:
print(X_train.value_counts())
print(X_test.value_counts())

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  MultipleLines  InternetService  OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges
1       0              0        0           1       1             0              2                1               1             1                 1            1            1                0         1                 3              20.200000       20.20000        5
                                                                                 1                0               0             0                 0            0            0                0         1                 2              69.900000       69.90000        4
                                                                                 2                1               1             1                 1            1            1                0         0                 3              20.200000       20.20000        4
0       0              0        0           1       1             0              1                0               0             0                 0            0            0                0         1                 3              70.150000       70.15000        3
1       0              0        0           1       1             0              0                0               0             0                 0            0            0                0         0                 2              45.300000       45.30000        3
                                                                                                                                                                                                                                                                       ..
0       0              1        0           13      0             1              0                0               0             2                 0            2            2                0         1                 0              48.750000       633.40000       1
                                                                  0              0                0               0             0                 0            0            0                0         1                 2              39.673527       483.49904       1
                                            12      1             2              0                2               0             2                 0            2            2                1         0                 2              78.850000       876.75000       1
                                                                  0              2                1               1             1                 1            1            1                2         1                 2              20.050000       264.55000       1
1       1              1        1           72      1             2              1                2               2             2                 2            2            2                2         1                 1              115.750000      8399.15000      1
Name: count, Length: 8231, dtype: int64
gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  MultipleLines  InternetService  OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges
1       0              0        0           1       1             0              2                1               1             1                 1            1            1                0         0                 3              20.00           20.00           2
0       0              0        0           1       0             1              0                0               0             0                 0            0            0                0         0                 3              24.40           24.40           1
1       0              0        0           52      1             2              1                0               2             2                 0            2            2                0         1                 2              103.05          5364.80         1
                                                                  0              1                0               2             0                 0            0            2                0         1                 2              85.35           4338.60         1
                                                                                                                  0             2                 0            0            2                0         1                 1              83.80           4331.40         1
                                                                                                                                                                                                                                                                       ..
0       0              1        1           12      1             0              2                1               1             1                 1            1            1                0         0                 0              19.40           198.10          1
                                                    0             1              0                2               0             0                 2            0            0                1         0                 1              33.15           444.75          1
                                            11      1             0              2                1               1             1                 1            1            1                2         0                 1              20.90           202.30          1
                                                                                                                                                                                             1         1                 3              20.00           196.35          1
1       1              1        1           72      1             2              1                2               2             2                 2            2            2                2         1                 0              114.95          8196.40         1
Name: count, Length: 1408, dtype: int64